### PR TITLE
Add TTL option for dht.request() and dht.ping()

### PR DESCRIPTION
**Pull request by LuKks**
Closes https://github.com/mafintosh/dht-rpc/issues/64

### CODE REVIEW

**Comment by LuKks** [comment]
The helper `_requestToPromise` is handling a few request options:
https://github.com/LuKks/dht-rpc/blob/c67630bf295d5de55ee328f8b6a8aba6a88ab4fb/index.js#L189

We could move it to inside of `Request` class, then we could simplifiy the `opts` part as we could pass it directly to `createRequest`, then just for the `Promise` part we can add a similar helper like `toPromise()`

**Comment by LuKks** [comment]
(but this `toPromise()` will not touch options, just take care of the `Promise` part)

**Comment by LuKks** [comment]
@mafintosh Ready!

**Review by kasperisager — APPROVED** [review]
Looks solid!

**Pull request merged**
