### PR TITLE
allocate new stacktrace for debugging

### PR DESCRIPTION
**Pull request by Raynos**

### CODE REVIEW

**Comment by mafintosh** [comment]
Can you change this to be functions on the error lib instead? ie

```
const err = errors.createTimeoutError()
const err = errors.createDestroyedError()
```

**Comment by Raynos** [comment]
:+1: sure will fix.

**Comment by Raynos** [comment]
Ok updated PR.

**Comment by mafintosh** [comment]
Looks good, merging + releasing when I’m at my laptop

**Comment by mafintosh** [comment]
5.0.6

**Pull request merged**
